language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

addons:
  apt:
    sources:
    - trusty
    - deadsnakes
    - sourceline: 'ppa:sergey-dryabzhinsky/packages'

install:
- sudo apt-get update
- sudo apt-get upgrade
- sudo apt-get install -y libzstd-dev

script:
- python setup.py test
- python setup.py clean -a
- python setup.py --legacy test
- python setup.py clean -a
- python setup.py --external test
- python setup.py clean -a
