language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

addons:
  apt:
    sources:
    - deadsnakes
    - sourceline: 'ppa:sergey-dryabzhinsky/packages'

install: sudo apt-get install libzstd-dev
script:
- python setup.py test
- python setup.py --legacy test
- python setup.py --external test
